# Generated by Django 2.2.10 on 2021-02-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
