# Generated by Django 2.2.10 on 2021-02-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210216_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
